// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Collections.Immutable;

namespace Cratis.Fundamentals.TypeDiscovery.Generator;

/// <summary>
/// Builds the C# source text for the generated <c>GeneratedTypeDiscoveryProvider</c> class.
/// </summary>
internal static class GeneratedSourceBuilder
{
    /// <summary>
    /// Builds the full source text for the generated provider from the collected analysis results.
    /// </summary>
    /// <param name="namedTypes">All type-of expressions for types discovered in the assembly.</param>
    /// <param name="contractsAndImplementors">The contract-to-implementors map entries.</param>
    /// <param name="conventionServiceBindings">The I&lt;X&gt;/&lt;X&gt; convention bindings.</param>
    /// <param name="conventionSelfBindings">The self-binding type entries.</param>
    /// <returns>The complete C# source text.</returns>
    public static string Build(
        ImmutableArray<string> namedTypes,
        ImmutableArray<(string ContractExpression, ImmutableArray<string> ImplementorExpressions)> contractsAndImplementors,
        ImmutableArray<(string ServiceExpression, string ImplementationExpression, string LifetimeExpression)> conventionServiceBindings,
        ImmutableArray<(string ImplementationExpression, string LifetimeExpression)> conventionSelfBindings)
    {
        var definedTypes = string.Join(",\n", namedTypes.Select(static name => $"        typeof({name})"));

        var generatedServiceBindings = string.Join(
            ",\n",
            conventionServiceBindings.Select(static b =>
                $"        new global::Cratis.DependencyInjection.ConventionServiceBinding(typeof({b.ServiceExpression}), typeof({b.ImplementationExpression}), {b.LifetimeExpression})"));

        var generatedSelfBindings = string.Join(
            ",\n",
            conventionSelfBindings.Select(static b =>
                $"        new global::Cratis.DependencyInjection.ConventionSelfBinding(typeof({b.ImplementationExpression}), {b.LifetimeExpression})"));

        return string.Join(
            "\n",
            [
                "// <auto-generated />",
                string.Empty,
                "namespace Cratis.Types.Generated;",
                string.Empty,
                "using System;",
                "using System.Collections.Generic;",
                "using System.Linq;",
                "using System.Reflection;",
                "using System.Runtime.CompilerServices;",
                string.Empty,
                "file sealed class GeneratedTypeDiscoveryProvider : global::Cratis.Types.ICanProvideAssembliesForDiscovery, global::Cratis.Types.ICanProvideContractToImplementorsForDiscovery, global::Cratis.DependencyInjection.ICanProvideConventionsForDependencyInjection",
                "{",
                "    public IEnumerable<Assembly> Assemblies => [typeof(GeneratedTypeDiscoveryProvider).Assembly];",
                string.Empty,
                "    public IEnumerable<Type> DefinedTypes =>",
                "    [",
                definedTypes,
                "    ];",
                string.Empty,
                "    public IEnumerable<global::Cratis.DependencyInjection.ConventionServiceBinding> ConventionServiceBindings =>",
                "    [",
                generatedServiceBindings,
                "    ];",
                string.Empty,
                "    public IEnumerable<global::Cratis.DependencyInjection.ConventionSelfBinding> SelfBindings =>",
                "    [",
                generatedSelfBindings,
                "    ];",
                string.Empty,
                "    public IDictionary<Type, IEnumerable<Type>> ContractsAndImplementors => new Dictionary<Type, IEnumerable<Type>>",
                "    {",
                ..contractsAndImplementors.Select(GetContractAndImplementorsMapEntry),
                "    };",
                string.Empty,
                "    public void Initialize()",
                "    {",
                "    }",
                "}",
                string.Empty,
                "file static class GeneratedTypeDiscoveryProviderRegistration",
                "{",
                "    [ModuleInitializer]",
                "    public static void Register() =>",
                "        global::Cratis.Types.GeneratedTypeDiscoveryRegistry.Register(new GeneratedTypeDiscoveryProvider());",
                "}"
            ]);
    }

    static string GetContractAndImplementorsMapEntry((string ContractExpression, ImmutableArray<string> ImplementorExpressions) entry) =>
        $"        [typeof({entry.ContractExpression})] = [{string.Join(", ", entry.ImplementorExpressions.Select(static i => $"typeof({i})"))}],";
}
